AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  python38:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: fmi-python38-v2
      ContentUri: .
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: makefile

  EchoFunction:
    Type: AWS::Serverless::Function
    Properties:
      # CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
    Metadata:
      BuildMethod: makefile
